version: "3.9"

services:
  matrimo-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: matrimomanager
    networks:
      - matrimo-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    volumes:
      - minio-data:/data
    networks:
      - matrimo-net
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local http://minio:9000 admin adminpassword;
      /usr/bin/mc mb local/matrimo-bucket;
      /usr/bin/mc policy set public local/matrimo-bucket;
      exit 0;
      "
    networks:
      - matrimo-net

networks:
  matrimo-net:

volumes:
  minio-data:
