/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PricingImport } from './routes/pricing'
import { Route as FeaturesImport } from './routes/features'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as privatePImport } from './routes/(private)/_p'
import { Route as authAuthImport } from './routes/(auth)/_auth'
import { Route as privatePProfileImport } from './routes/(private)/_p.profile'
import { Route as authAuthGoogleCallbackImport } from './routes/(auth)/_auth.google.callback'
import { Route as authAuthAuthSignupImport } from './routes/(auth)/_auth.auth.signup'
import { Route as authAuthAuthSigninImport } from './routes/(auth)/_auth.auth.signin'

// Create Virtual Routes

const privateImport = createFileRoute('/(private)')()
const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const privateRoute = privateImport.update({
  id: '/(private)',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const FeaturesRoute = FeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const privatePRoute = privatePImport.update({
  id: '/_p',
  getParentRoute: () => privateRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)

const privatePProfileRoute = privatePProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => privatePRoute,
} as any)

const authAuthGoogleCallbackRoute = authAuthGoogleCallbackImport.update({
  id: '/google/callback',
  path: '/google/callback',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthAuthSignupRoute = authAuthAuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthAuthSigninRoute = authAuthAuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => authAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof authRoute
    }
    '/(private)': {
      id: '/(private)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateImport
      parentRoute: typeof rootRoute
    }
    '/(private)/_p': {
      id: '/(private)/_p'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatePImport
      parentRoute: typeof privateRoute
    }
    '/(private)/_p/profile': {
      id: '/(private)/_p/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privatePProfileImport
      parentRoute: typeof privatePImport
    }
    '/(auth)/_auth/auth/signin': {
      id: '/(auth)/_auth/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof authAuthAuthSigninImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/auth/signup': {
      id: '/(auth)/_auth/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthAuthSignupImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/google/callback': {
      id: '/(auth)/_auth/google/callback'
      path: '/google/callback'
      fullPath: '/google/callback'
      preLoaderRoute: typeof authAuthGoogleCallbackImport
      parentRoute: typeof authAuthImport
    }
  }
}

// Create and export the route tree

interface authAuthRouteChildren {
  authAuthAuthSigninRoute: typeof authAuthAuthSigninRoute
  authAuthAuthSignupRoute: typeof authAuthAuthSignupRoute
  authAuthGoogleCallbackRoute: typeof authAuthGoogleCallbackRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthAuthSigninRoute: authAuthAuthSigninRoute,
  authAuthAuthSignupRoute: authAuthAuthSignupRoute,
  authAuthGoogleCallbackRoute: authAuthGoogleCallbackRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface privatePRouteChildren {
  privatePProfileRoute: typeof privatePProfileRoute
}

const privatePRouteChildren: privatePRouteChildren = {
  privatePProfileRoute: privatePProfileRoute,
}

const privatePRouteWithChildren = privatePRoute._addFileChildren(
  privatePRouteChildren,
)

interface privateRouteChildren {
  privatePRoute: typeof privatePRouteWithChildren
}

const privateRouteChildren: privateRouteChildren = {
  privatePRoute: privatePRouteWithChildren,
}

const privateRouteWithChildren =
  privateRoute._addFileChildren(privateRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof privatePRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof privatePProfileRoute
  '/auth/signin': typeof authAuthAuthSigninRoute
  '/auth/signup': typeof authAuthAuthSignupRoute
  '/google/callback': typeof authAuthGoogleCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof privatePRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof privatePProfileRoute
  '/auth/signin': typeof authAuthAuthSigninRoute
  '/auth/signup': typeof authAuthAuthSignupRoute
  '/google/callback': typeof authAuthGoogleCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(private)': typeof privateRouteWithChildren
  '/(private)/_p': typeof privatePRouteWithChildren
  '/(private)/_p/profile': typeof privatePProfileRoute
  '/(auth)/_auth/auth/signin': typeof authAuthAuthSigninRoute
  '/(auth)/_auth/auth/signup': typeof authAuthAuthSignupRoute
  '/(auth)/_auth/google/callback': typeof authAuthGoogleCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/profile'
    | '/auth/signin'
    | '/auth/signup'
    | '/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/profile'
    | '/auth/signin'
    | '/auth/signup'
    | '/google/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(private)'
    | '/(private)/_p'
    | '/(private)/_p/profile'
    | '/(auth)/_auth/auth/signin'
    | '/(auth)/_auth/auth/signup'
    | '/(auth)/_auth/google/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  authRoute: typeof authRouteWithChildren
  privateRoute: typeof privateRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  authRoute: authRouteWithChildren,
  privateRoute: privateRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/features",
        "/pricing",
        "/(auth)",
        "/(private)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/features": {
      "filePath": "features.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth"
      ]
    },
    "/(auth)/_auth": {
      "filePath": "(auth)/_auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth/auth/signin",
        "/(auth)/_auth/auth/signup",
        "/(auth)/_auth/google/callback"
      ]
    },
    "/(private)": {
      "filePath": "(private)",
      "children": [
        "/(private)/_p"
      ]
    },
    "/(private)/_p": {
      "filePath": "(private)/_p.tsx",
      "parent": "/(private)",
      "children": [
        "/(private)/_p/profile"
      ]
    },
    "/(private)/_p/profile": {
      "filePath": "(private)/_p.profile.tsx",
      "parent": "/(private)/_p"
    },
    "/(auth)/_auth/auth/signin": {
      "filePath": "(auth)/_auth.auth.signin.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/auth/signup": {
      "filePath": "(auth)/_auth.auth.signup.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/google/callback": {
      "filePath": "(auth)/_auth.google.callback.tsx",
      "parent": "/(auth)/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
