export const AUTH_TOKEN_KEY = "auth_token";

export const CANVAS_PRESETS = [
  {
    id: "portrait-4x6",
    name: "4 × 6 in",
    type: "Portrait",
    width: 384,
    height: 576,
    label: "4 × 6 in",
  },
  {
    id: "portrait-5x7",
    name: "5 × 7 in",
    type: "Portrait",
    width: 480,
    height: 672,
    label: "5 × 7 in",
  },
  {
    id: "portrait-6x8",
    name: "6 × 8 in",
    type: "Portrait",
    width: 576,
    height: 768,
    label: "6 × 8 in",
  },
  {
    id: "portrait-a4",
    name: "A4",
    type: "Portrait",
    width: 794,
    height: 1122,
    label: "A4",
  },
  {
    id: "portrait-a5",
    name: "A5",
    type: "Portrait",
    width: 560,
    height: 794,
    label: "A5",
  },
  {
    id: "landscape-4x6",
    name: "6 × 4 in",
    type: "Landscape",
    width: 576,
    height: 384,
    label: "6 × 4 in",
  },
  {
    id: "landscape-5x7",
    name: "7 × 5 in",
    type: "Landscape",
    width: 672,
    height: 480,
    label: "7 × 5 in",
  },
  {
    id: "landscape-6x8",
    name: "8 × 6 in",
    type: "Landscape",
    width: 768,
    height: 576,
    label: "8 × 6 in",
  },
  {
    id: "landscape-a4",
    name: "A4 Landscape",
    type: "Landscape",
    width: 1122,
    height: 794,
    label: "A4 Landscape",
  },
  {
    id: "landscape-a5",
    name: "A5 Landscape",
    type: "Landscape",
    width: 794,
    height: 560,
    label: "A5 Landscape",
  },
] as const;
